// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson5326d961DecodeGithubComGoParkMailRu20242NovaCodeInternalModels(in *jlexer.Lexer, out *PlaylistTracks) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(PlaylistTracks, 0, 8)
			} else {
				*out = PlaylistTracks{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 *PlaylistTrack
			if in.IsNull() {
				in.Skip()
				v1 = nil
			} else {
				if v1 == nil {
					v1 = new(PlaylistTrack)
				}
				(*v1).UnmarshalEasyJSON(in)
			}
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5326d961EncodeGithubComGoParkMailRu20242NovaCodeInternalModels(out *jwriter.Writer, in PlaylistTracks) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			if v3 == nil {
				out.RawString("null")
			} else {
				(*v3).MarshalEasyJSON(out)
			}
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v PlaylistTracks) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5326d961EncodeGithubComGoParkMailRu20242NovaCodeInternalModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PlaylistTracks) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5326d961EncodeGithubComGoParkMailRu20242NovaCodeInternalModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PlaylistTracks) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5326d961DecodeGithubComGoParkMailRu20242NovaCodeInternalModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PlaylistTracks) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5326d961DecodeGithubComGoParkMailRu20242NovaCodeInternalModels(l, v)
}
func easyjson5326d961DecodeGithubComGoParkMailRu20242NovaCodeInternalModels1(in *jlexer.Lexer, out *PlaylistTrack) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "ID":
			out.ID = uint64(in.Uint64())
		case "PlaylistID":
			out.PlaylistID = uint64(in.Uint64())
		case "TrackOrderInPlaylist":
			out.TrackOrderInPlaylist = uint64(in.Uint64())
		case "TrackID":
			out.TrackID = uint64(in.Uint64())
		case "CreatedAt":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		case "UpdatedAt":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.UpdatedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5326d961EncodeGithubComGoParkMailRu20242NovaCodeInternalModels1(out *jwriter.Writer, in PlaylistTrack) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ID\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.ID))
	}
	{
		const prefix string = ",\"PlaylistID\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.PlaylistID))
	}
	{
		const prefix string = ",\"TrackOrderInPlaylist\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.TrackOrderInPlaylist))
	}
	{
		const prefix string = ",\"TrackID\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.TrackID))
	}
	{
		const prefix string = ",\"CreatedAt\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"UpdatedAt\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PlaylistTrack) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5326d961EncodeGithubComGoParkMailRu20242NovaCodeInternalModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PlaylistTrack) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5326d961EncodeGithubComGoParkMailRu20242NovaCodeInternalModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PlaylistTrack) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5326d961DecodeGithubComGoParkMailRu20242NovaCodeInternalModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PlaylistTrack) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5326d961DecodeGithubComGoParkMailRu20242NovaCodeInternalModels1(l, v)
}
