{
 "title": "Workload",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(backend_http_requests_total[5m])) by (microservice, method, url)",
     "legendFormat": "{{microservice}}: {{method}} {{url}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(backend_http_request_duration_seconds_sum[5m])) by (microservice, method, url) / avg(rate(backend_http_request_duration_seconds_count[5m])) by (microservice, method, url)",
     "legendFormat": "{{microservice}}: {{method}} {{url}}"
    }
   ]
  },
  {
   "title": "Request Rate by Method and URL",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(backend_http_requests_total[5m])) by (microservice, method, url)",
     "legendFormat": "{{microservice}}: {{method}} {{url}}"
    }
   ]
  },
  {
   "title": "Request Rate by Status Code",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(backend_http_requests_total[5m])) by (microservice, status)",
     "legendFormat": "{{microservice}}: {{status}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(backend_http_errors_total[5m])) by (microservice, method, url, status)",
     "legendFormat": "{{microservice}}: {{method}} {{url}} {{status}}"
    }
   ]
  }
 ]
}