FROM golang:1.22-alpine3.20 AS builder

WORKDIR /service

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o bin/main ./cmd/main.go

FROM alpine:latest

RUN apk update && apk upgrade
RUN rm -rf /var/cache/apk/* && \
    rm -rf /tmp/*

RUN adduser -D guest
USER guest

WORKDIR /service

COPY --from=builder /service/bin/main ./bin/

EXPOSE 8080

ENTRYPOINT ["./bin/main"]