services:
  novamusic-backend:
    image: daronenko/novamusic-backend:${VERSION}
    container_name: novamusic-backend
    platform: linux/amd64
    env_file: .prod.env
    build:
      dockerfile: docker/Dockerfile.${ENV}
      context: ..
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - prometheus
      - prometheus-exporters
    volumes:
      - /etc/ssl/nova-music.ru:/etc/ssl/nova-music.ru

  postgres:
    container_name: novamusic-postgres
    image: postgres:16
    platform: linux/amd64
    env_file: .prod.env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: on-failure
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 2s
      timeout: 3s
      retries: 3
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - prometheus

  migrations:
    container_name: novamusic-postgres-migrations
    image: ghcr.io/kukymbr/goose-docker:3.22.1
    platform: linux/amd64
    restart: no
    env_file: .prod.env
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=host=postgres port=${POSTGRES_PORT} user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} dbname=${POSTGRES_DB}
      - GOOSE_VERBOSE=true
    volumes:
      - ../internal/db/postgres/migrations:/migrations
    networks:
      - prometheus

  minio:
    container_name: novamusic-minio
    image: minio/minio:latest
    platform: linux/amd64
    restart: always
    env_file: .prod.env
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
      - MINIO_SERVER_URL=https://${HOST}:8010
      - MINIO_BROWSER_REDIRECT_URL=https://${HOST}
    ports:
      - 8010:9000
      - 8011:9001
    command: server --console-address :9001 /data
    volumes:
      - minio-volume:/data
      - /etc/ssl/nova-music.ru:/root/.minio/certs:ro
    networks:
      - prometheus

  minio-client:
    container_name: minio-client
    image: minio/mc:latest
    env_file: .prod.env
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host rm local;
      /usr/bin/mc config host add --quiet --api s3v4 local https://minio:9000 ${MINIO_USER} ${MINIO_PASSWORD};

      /usr/bin/mc mb --quiet local/avatars;
      /usr/bin/mc policy set public local/avatars;

      /usr/bin/mc mb --quiet local/images;
      /usr/bin/mc policy set public local/images;

      /usr/bin/mc mb --quiet local/tracks;
      /usr/bin/mc policy set public local/tracks;
      "
    networks:
      - prometheus
  
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.rapl'
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - prometheus-exporters
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    env_file: .dev.env
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus/'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=365d'
      - '--web.external-url=${PROMETHEUS_URL}'
      - '--web.enable-admin-api'
    restart: unless-stopped
    expose:
      - 8002
    ports:
      - 8002:9090
    networks:
      - prometheus
      - prometheus-exporters
    depends_on:
      - node-exporter
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    env_file: .dev.env
    environment:
      - GF_SECURITY_ADMIN_USER
      - GF_SECURITY_ADMIN_PASSWORD
      - GF_DEFAULT_INSTANCE_NAME=${HOST}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ENABLE_GZIP=true
      - GF_SERVER_ROOT_URL
    restart: unless-stopped
    ports:
      - 8003:3000
    networks:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - alertmanager-data:/alertmanager
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ./alertmanager/telegram.tmpl:/etc/alertmanager/telegram.tmpl
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=${ALERTMANAGER_EXTERNAL_URL}'
    restart: unless-stopped
    expose:
      - 8004
    ports:
      - 8004:9093
    networks:
      - prometheus

volumes:
  postgres-volume:
  minio-volume:
  prometheus-data:
  grafana-data:
  alertmanager-data:
