services:
  auth:
    container_name: auth
    build:
      dockerfile: docker/Dockerfile.dev
      context: ..
    env_file: ../config/.dev.env
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: auth-postgres
    image: postgres:16
    env_file: ../config/.dev.env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    restart: on-failure
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 2s
      timeout: 3s
      retries: 3
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
