FROM golang:1.22-alpine3.20 AS builder

WORKDIR /service

COPY ./ ./

RUN go mod tidy
RUN go build -o bin/main cmd/main.go

FROM alpine:3.20

WORKDIR /service

RUN apk update && apk add bash && apk --no-cache add tzdata

COPY --from=builder /service/bin/main ./bin/

ENTRYPOINT [ "/service/bin/main" ]
