service:
  http:
    port: :8080
    readTimeout: 10
    writeTimeout: 10
    idleTimeout: 120
    contextTimeout: 5
  
  grpc:
    port: :9000
    maxConnectionIdle: 5
    timeout: 15
    maxConnectionAge: 5
    time: 120

  cors:
    allowOrigin: "http://localhost:3000"
    allowMethods: "POST,GET,OPTIONS,PUT,DELETE"
    allowHeaders: "Content-Type,X-Csrf-Token"
    allowCredentials: true
    exposeHeaders: "X-Csrf-Token"

  logger:
    level: debug
    format: json

  auth:
    csrf:
      headerName: X-Csrf-Token

    jwt:
      expire: 3600
      cookie:
        name: jwt-token
        maxAge: 86400
        secure: false
        httpOnly: true

postgres:
  host: postgres
  sslMode: false
  driver: postgres

  maxOpenConns: 100
  connMaxLifetime: 120
  maxIdleConns: 30
  connMaxIdleTime: 20

minio:
  url: minio:9000
  sslMode: false
