service:
  port: :8080
  readTimeout: 10
  writeTimeout: 10
  idleTimeout: 120
  contextTimeout: 5

  cors:
    allowOrigin: "http://185.241.194.24"
    allowMethods: "POST,GET,OPTIONS,PUT,DELETE"
    allowHeaders: "Content-Type,X-Csrf-Token"
    allowCredentials: true
    exposeHeaders: "C-Csrf-Token"

  logger:
    level: info
    format: json

  auth:
    csrf:
      headerName: C-Csrf-Token
      salt: yD5pwD0JG03NxFAz9VAOtbba6I7kPv2deg3C7SpEZUk=

    jwt:
      secret: secret
      expire: 3600
      cookie:
        name: jwt-token
        maxAge: 86400
        secure: false
        httpOnly: true

postgres:
  host: postgres
  port: 5432
  user: user
  password: password
  dbName: db
  sslMode: false
  driver: postgres

  maxOpenConns: 60
  connMaxLifetime: 120
  maxIdleConns: 30
  connMaxIdleTime: 20

minio:
  externalURL: http://185.241.194.24:9000
  innerURL: minio:9000
  user: user
  password: password
  sslMode: false
