service:
  port: :8080
  readTimeout: 10
  writeTimeout: 10
  idleTimeout: 120
  contextTimeout: 5

  cors:
    allowOrigin: "http://185.241.194.24"
    allowMethods: "POST,GET,OPTIONS,PUT,DELETE"
    allowHeaders: "Content-Type,X-Csrf-Token"
    allowCredentials: true
    exposeHeaders: "X-Csrf-Token"

  logger:
    level: info
    format: json

  auth:
    csrf:
      headerName: X-Csrf-Token

    jwt:
      expire: 3600
      cookie:
        name: jwt-token
        maxAge: 86400
        secure: false
        httpOnly: true

postgres:
  host: postgres
  sslMode: false
  driver: postgres

  maxOpenConns: 60
  connMaxLifetime: 120
  maxIdleConns: 30
  connMaxIdleTime: 20

minio:
  externalURL: http://185.241.194.24:8010
  innerURL: minio:9000
  sslMode: false