// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson56de76c1DecodeGithubComGoParkMailRu20242NovaCodeMicroservicesTrackDto(in *jlexer.Lexer, out *TrackDTOs) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(TrackDTOs, 0, 8)
			} else {
				*out = TrackDTOs{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 *TrackDTO
			if in.IsNull() {
				in.Skip()
				v1 = nil
			} else {
				if v1 == nil {
					v1 = new(TrackDTO)
				}
				(*v1).UnmarshalEasyJSON(in)
			}
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20242NovaCodeMicroservicesTrackDto(out *jwriter.Writer, in TrackDTOs) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			if v3 == nil {
				out.RawString("null")
			} else {
				(*v3).MarshalEasyJSON(out)
			}
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v TrackDTOs) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20242NovaCodeMicroservicesTrackDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TrackDTOs) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20242NovaCodeMicroservicesTrackDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TrackDTOs) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20242NovaCodeMicroservicesTrackDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TrackDTOs) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20242NovaCodeMicroservicesTrackDto(l, v)
}
func easyjson56de76c1DecodeGithubComGoParkMailRu20242NovaCodeMicroservicesTrackDto1(in *jlexer.Lexer, out *TrackDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = uint64(in.Uint64())
		case "name":
			out.Name = string(in.String())
		case "duration":
			out.Duration = uint64(in.Uint64())
		case "filepath":
			out.FilePath = string(in.String())
		case "image":
			out.Image = string(in.String())
		case "artistName":
			out.ArtistName = string(in.String())
		case "artistID":
			out.ArtistID = uint64(in.Uint64())
		case "albumName":
			out.AlbumName = string(in.String())
		case "albumID":
			out.AlbumID = uint64(in.Uint64())
		case "release":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.ReleaseDate).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComGoParkMailRu20242NovaCodeMicroservicesTrackDto1(out *jwriter.Writer, in TrackDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"duration\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Duration))
	}
	{
		const prefix string = ",\"filepath\":"
		out.RawString(prefix)
		out.String(string(in.FilePath))
	}
	{
		const prefix string = ",\"image\":"
		out.RawString(prefix)
		out.String(string(in.Image))
	}
	{
		const prefix string = ",\"artistName\":"
		out.RawString(prefix)
		out.String(string(in.ArtistName))
	}
	{
		const prefix string = ",\"artistID\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.ArtistID))
	}
	{
		const prefix string = ",\"albumName\":"
		out.RawString(prefix)
		out.String(string(in.AlbumName))
	}
	{
		const prefix string = ",\"albumID\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.AlbumID))
	}
	{
		const prefix string = ",\"release\":"
		out.RawString(prefix)
		out.Raw((in.ReleaseDate).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TrackDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComGoParkMailRu20242NovaCodeMicroservicesTrackDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TrackDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComGoParkMailRu20242NovaCodeMicroservicesTrackDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TrackDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComGoParkMailRu20242NovaCodeMicroservicesTrackDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TrackDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComGoParkMailRu20242NovaCodeMicroservicesTrackDto1(l, v)
}
