global:
  resolve_timeout: 5m
  http_config:
    follow_redirects: true
  telegram_api_url: "https://api.telegram.org"

route:
  receiver: "telegram"
  continue: false

receivers:
  - name: "telegram"
    telegram_configs:
      - send_resolved: true
        http_config:
          follow_redirects: true
        api_url: "https://api.telegram.org"
        bot_token: ""
        chat_id: ""
        message: '{{ template "telegram.default" . }}'
        parse_mode: "HTML"

templates:
  - /etc/alertmanager/telegram.tmpl
