global:
  scrape_interval:     20s
  evaluation_interval: 20s

rule_files:
  - 'alerts/*.yml'

scrape_configs:
  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['prometheus:9090']
    
  - job_name: 'novamusic-backend'
    scrape_interval: 1m
    static_configs:
      - targets: ['novamusic-backend:8080']

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:  ['alertmanager:9093']
