// // Code generated by protoc-gen-go. DO NOT EDIT.
// // versions:
// // 	protoc-gen-go v1.35.2
// // 	protoc        v3.12.4
// // source: album.proto

package proto

// import (
// 	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
// 	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
// 	reflect "reflect"
// 	sync "sync"
// )

// const (
// 	// Verify that this generated code is sufficiently up-to-date.
// 	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
// 	// Verify that runtime/protoimpl is sufficiently up-to-date.
// 	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
// )

// type SearchAlbumRequest struct {
// 	state         protoimpl.MessageState
// 	sizeCache     protoimpl.SizeCache
// 	unknownFields protoimpl.UnknownFields

// 	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
// }

// func (x *SearchAlbumRequest) Reset() {
// 	*x = SearchAlbumRequest{}
// 	mi := &file_album_proto_msgTypes[0]
// 	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
// 	ms.StoreMessageInfo(mi)
// }

// func (x *SearchAlbumRequest) String() string {
// 	return protoimpl.X.MessageStringOf(x)
// }

// func (*SearchAlbumRequest) ProtoMessage() {}

// func (x *SearchAlbumRequest) ProtoReflect() protoreflect.Message {
// 	mi := &file_album_proto_msgTypes[0]
// 	if x != nil {
// 		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
// 		if ms.LoadMessageInfo() == nil {
// 			ms.StoreMessageInfo(mi)
// 		}
// 		return ms
// 	}
// 	return mi.MessageOf(x)
// }

// // Deprecated: Use SearchAlbumRequest.ProtoReflect.Descriptor instead.
// func (*SearchAlbumRequest) Descriptor() ([]byte, []int) {
// 	return file_album_proto_rawDescGZIP(), []int{0}
// }

// func (x *SearchAlbumRequest) GetQuery() string {
// 	if x != nil {
// 		return x.Query
// 	}
// 	return ""
// }

// type SearchAlbumResponse struct {
// 	state         protoimpl.MessageState
// 	sizeCache     protoimpl.SizeCache
// 	unknownFields protoimpl.UnknownFields

// 	Albums []*Album `protobuf:"bytes,1,rep,name=albums,proto3" json:"albums,omitempty"`
// }

// func (x *SearchAlbumResponse) Reset() {
// 	*x = SearchAlbumResponse{}
// 	mi := &file_album_proto_msgTypes[1]
// 	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
// 	ms.StoreMessageInfo(mi)
// }

// func (x *SearchAlbumResponse) String() string {
// 	return protoimpl.X.MessageStringOf(x)
// }

// func (*SearchAlbumResponse) ProtoMessage() {}

// func (x *SearchAlbumResponse) ProtoReflect() protoreflect.Message {
// 	mi := &file_album_proto_msgTypes[1]
// 	if x != nil {
// 		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
// 		if ms.LoadMessageInfo() == nil {
// 			ms.StoreMessageInfo(mi)
// 		}
// 		return ms
// 	}
// 	return mi.MessageOf(x)
// }

// // Deprecated: Use SearchAlbumResponse.ProtoReflect.Descriptor instead.
// func (*SearchAlbumResponse) Descriptor() ([]byte, []int) {
// 	return file_album_proto_rawDescGZIP(), []int{1}
// }

// func (x *SearchAlbumResponse) GetAlbums() []*Album {
// 	if x != nil {
// 		return x.Albums
// 	}
// 	return nil
// }

// type ViewAlbumRequest struct {
// 	state         protoimpl.MessageState
// 	sizeCache     protoimpl.SizeCache
// 	unknownFields protoimpl.UnknownFields

// 	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
// }

// func (x *ViewAlbumRequest) Reset() {
// 	*x = ViewAlbumRequest{}
// 	mi := &file_album_proto_msgTypes[2]
// 	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
// 	ms.StoreMessageInfo(mi)
// }

// func (x *ViewAlbumRequest) String() string {
// 	return protoimpl.X.MessageStringOf(x)
// }

// func (*ViewAlbumRequest) ProtoMessage() {}

// func (x *ViewAlbumRequest) ProtoReflect() protoreflect.Message {
// 	mi := &file_album_proto_msgTypes[2]
// 	if x != nil {
// 		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
// 		if ms.LoadMessageInfo() == nil {
// 			ms.StoreMessageInfo(mi)
// 		}
// 		return ms
// 	}
// 	return mi.MessageOf(x)
// }

// // Deprecated: Use ViewAlbumRequest.ProtoReflect.Descriptor instead.
// func (*ViewAlbumRequest) Descriptor() ([]byte, []int) {
// 	return file_album_proto_rawDescGZIP(), []int{2}
// }

// func (x *ViewAlbumRequest) GetId() uint64 {
// 	if x != nil {
// 		return x.Id
// 	}
// 	return 0
// }

// type ViewAlbumResponse struct {
// 	state         protoimpl.MessageState
// 	sizeCache     protoimpl.SizeCache
// 	unknownFields protoimpl.UnknownFields

// 	Album *Album `protobuf:"bytes,1,opt,name=album,proto3" json:"album,omitempty"`
// }

// func (x *ViewAlbumResponse) Reset() {
// 	*x = ViewAlbumResponse{}
// 	mi := &file_album_proto_msgTypes[3]
// 	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
// 	ms.StoreMessageInfo(mi)
// }

// func (x *ViewAlbumResponse) String() string {
// 	return protoimpl.X.MessageStringOf(x)
// }

// func (*ViewAlbumResponse) ProtoMessage() {}

// func (x *ViewAlbumResponse) ProtoReflect() protoreflect.Message {
// 	mi := &file_album_proto_msgTypes[3]
// 	if x != nil {
// 		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
// 		if ms.LoadMessageInfo() == nil {
// 			ms.StoreMessageInfo(mi)
// 		}
// 		return ms
// 	}
// 	return mi.MessageOf(x)
// }

// // Deprecated: Use ViewAlbumResponse.ProtoReflect.Descriptor instead.
// func (*ViewAlbumResponse) Descriptor() ([]byte, []int) {
// 	return file_album_proto_rawDescGZIP(), []int{3}
// }

// func (x *ViewAlbumResponse) GetAlbum() *Album {
// 	if x != nil {
// 		return x.Album
// 	}
// 	return nil
// }

// type GetAllAlbumsRequest struct {
// 	state         protoimpl.MessageState
// 	sizeCache     protoimpl.SizeCache
// 	unknownFields protoimpl.UnknownFields
// }

// func (x *GetAllAlbumsRequest) Reset() {
// 	*x = GetAllAlbumsRequest{}
// 	mi := &file_album_proto_msgTypes[4]
// 	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
// 	ms.StoreMessageInfo(mi)
// }

// func (x *GetAllAlbumsRequest) String() string {
// 	return protoimpl.X.MessageStringOf(x)
// }

// func (*GetAllAlbumsRequest) ProtoMessage() {}

// func (x *GetAllAlbumsRequest) ProtoReflect() protoreflect.Message {
// 	mi := &file_album_proto_msgTypes[4]
// 	if x != nil {
// 		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
// 		if ms.LoadMessageInfo() == nil {
// 			ms.StoreMessageInfo(mi)
// 		}
// 		return ms
// 	}
// 	return mi.MessageOf(x)
// }

// // Deprecated: Use GetAllAlbumsRequest.ProtoReflect.Descriptor instead.
// func (*GetAllAlbumsRequest) Descriptor() ([]byte, []int) {
// 	return file_album_proto_rawDescGZIP(), []int{4}
// }

// type GetAllAlbumsResponse struct {
// 	state         protoimpl.MessageState
// 	sizeCache     protoimpl.SizeCache
// 	unknownFields protoimpl.UnknownFields

// 	Albums []*Album `protobuf:"bytes,1,rep,name=albums,proto3" json:"albums,omitempty"`
// }

// func (x *GetAllAlbumsResponse) Reset() {
// 	*x = GetAllAlbumsResponse{}
// 	mi := &file_album_proto_msgTypes[5]
// 	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
// 	ms.StoreMessageInfo(mi)
// }

// func (x *GetAllAlbumsResponse) String() string {
// 	return protoimpl.X.MessageStringOf(x)
// }

// func (*GetAllAlbumsResponse) ProtoMessage() {}

// func (x *GetAllAlbumsResponse) ProtoReflect() protoreflect.Message {
// 	mi := &file_album_proto_msgTypes[5]
// 	if x != nil {
// 		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
// 		if ms.LoadMessageInfo() == nil {
// 			ms.StoreMessageInfo(mi)
// 		}
// 		return ms
// 	}
// 	return mi.MessageOf(x)
// }

// // Deprecated: Use GetAllAlbumsResponse.ProtoReflect.Descriptor instead.
// func (*GetAllAlbumsResponse) Descriptor() ([]byte, []int) {
// 	return file_album_proto_rawDescGZIP(), []int{5}
// }

// func (x *GetAllAlbumsResponse) GetAlbums() []*Album {
// 	if x != nil {
// 		return x.Albums
// 	}
// 	return nil
// }

// type GetAllAlbumsByArtistIDRequest struct {
// 	state         protoimpl.MessageState
// 	sizeCache     protoimpl.SizeCache
// 	unknownFields protoimpl.UnknownFields

// 	ArtistId uint64 `protobuf:"varint,1,opt,name=artist_id,json=artistId,proto3" json:"artist_id,omitempty"`
// }

// func (x *GetAllAlbumsByArtistIDRequest) Reset() {
// 	*x = GetAllAlbumsByArtistIDRequest{}
// 	mi := &file_album_proto_msgTypes[6]
// 	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
// 	ms.StoreMessageInfo(mi)
// }

// func (x *GetAllAlbumsByArtistIDRequest) String() string {
// 	return protoimpl.X.MessageStringOf(x)
// }

// func (*GetAllAlbumsByArtistIDRequest) ProtoMessage() {}

// func (x *GetAllAlbumsByArtistIDRequest) ProtoReflect() protoreflect.Message {
// 	mi := &file_album_proto_msgTypes[6]
// 	if x != nil {
// 		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
// 		if ms.LoadMessageInfo() == nil {
// 			ms.StoreMessageInfo(mi)
// 		}
// 		return ms
// 	}
// 	return mi.MessageOf(x)
// }

// // Deprecated: Use GetAllAlbumsByArtistIDRequest.ProtoReflect.Descriptor instead.
// func (*GetAllAlbumsByArtistIDRequest) Descriptor() ([]byte, []int) {
// 	return file_album_proto_rawDescGZIP(), []int{6}
// }

// func (x *GetAllAlbumsByArtistIDRequest) GetArtistId() uint64 {
// 	if x != nil {
// 		return x.ArtistId
// 	}
// 	return 0
// }

// type GetAllAlbumsByArtistIDResponse struct {
// 	state         protoimpl.MessageState
// 	sizeCache     protoimpl.SizeCache
// 	unknownFields protoimpl.UnknownFields

// 	Albums []*Album `protobuf:"bytes,1,rep,name=albums,proto3" json:"albums,omitempty"`
// }

// func (x *GetAllAlbumsByArtistIDResponse) Reset() {
// 	*x = GetAllAlbumsByArtistIDResponse{}
// 	mi := &file_album_proto_msgTypes[7]
// 	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
// 	ms.StoreMessageInfo(mi)
// }

// func (x *GetAllAlbumsByArtistIDResponse) String() string {
// 	return protoimpl.X.MessageStringOf(x)
// }

// func (*GetAllAlbumsByArtistIDResponse) ProtoMessage() {}

// func (x *GetAllAlbumsByArtistIDResponse) ProtoReflect() protoreflect.Message {
// 	mi := &file_album_proto_msgTypes[7]
// 	if x != nil {
// 		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
// 		if ms.LoadMessageInfo() == nil {
// 			ms.StoreMessageInfo(mi)
// 		}
// 		return ms
// 	}
// 	return mi.MessageOf(x)
// }

// // Deprecated: Use GetAllAlbumsByArtistIDResponse.ProtoReflect.Descriptor instead.
// func (*GetAllAlbumsByArtistIDResponse) Descriptor() ([]byte, []int) {
// 	return file_album_proto_rawDescGZIP(), []int{7}
// }

// func (x *GetAllAlbumsByArtistIDResponse) GetAlbums() []*Album {
// 	if x != nil {
// 		return x.Albums
// 	}
// 	return nil
// }

// type Album struct {
// 	state         protoimpl.MessageState
// 	sizeCache     protoimpl.SizeCache
// 	unknownFields protoimpl.UnknownFields

// 	Id            uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
// 	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
// 	Artist        string `protobuf:"bytes,3,opt,name=artist,proto3" json:"artist,omitempty"`
// 	Genre         string `protobuf:"bytes,4,opt,name=genre,proto3" json:"genre,omitempty"`
// 	ReleaseYear   uint32 `protobuf:"varint,5,opt,name=release_year,json=releaseYear,proto3" json:"release_year,omitempty"`
// 	CoverImageUrl string `protobuf:"bytes,6,opt,name=cover_image_url,json=coverImageUrl,proto3" json:"cover_image_url,omitempty"`
// }

// func (x *Album) Reset() {
// 	*x = Album{}
// 	mi := &file_album_proto_msgTypes[8]
// 	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
// 	ms.StoreMessageInfo(mi)
// }

// func (x *Album) String() string {
// 	return protoimpl.X.MessageStringOf(x)
// }

// func (*Album) ProtoMessage() {}

// func (x *Album) ProtoReflect() protoreflect.Message {
// 	mi := &file_album_proto_msgTypes[8]
// 	if x != nil {
// 		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
// 		if ms.LoadMessageInfo() == nil {
// 			ms.StoreMessageInfo(mi)
// 		}
// 		return ms
// 	}
// 	return mi.MessageOf(x)
// }

// // Deprecated: Use Album.ProtoReflect.Descriptor instead.
// func (*Album) Descriptor() ([]byte, []int) {
// 	return file_album_proto_rawDescGZIP(), []int{8}
// }

// func (x *Album) GetId() uint64 {
// 	if x != nil {
// 		return x.Id
// 	}
// 	return 0
// }

// func (x *Album) GetName() string {
// 	if x != nil {
// 		return x.Name
// 	}
// 	return ""
// }

// func (x *Album) GetArtist() string {
// 	if x != nil {
// 		return x.Artist
// 	}
// 	return ""
// }

// func (x *Album) GetGenre() string {
// 	if x != nil {
// 		return x.Genre
// 	}
// 	return ""
// }

// func (x *Album) GetReleaseYear() uint32 {
// 	if x != nil {
// 		return x.ReleaseYear
// 	}
// 	return 0
// }

// func (x *Album) GetCoverImageUrl() string {
// 	if x != nil {
// 		return x.CoverImageUrl
// 	}
// 	return ""
// }

// var File_album_proto protoreflect.FileDescriptor

// var file_album_proto_rawDesc = []byte{
// 	0x0a, 0x0b, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
// 	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x12, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x6c,
// 	0x62, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75,
// 	0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79,
// 	0x22, 0x3b, 0x0a, 0x13, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x52,
// 	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x61, 0x6c, 0x62, 0x75, 0x6d,
// 	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
// 	0x41, 0x6c, 0x62, 0x75, 0x6d, 0x52, 0x06, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x73, 0x22, 0x22, 0x0a,
// 	0x10, 0x56, 0x69, 0x65, 0x77, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
// 	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69,
// 	0x64, 0x22, 0x37, 0x0a, 0x11, 0x56, 0x69, 0x65, 0x77, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x52, 0x65,
// 	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x18,
// 	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x6c,
// 	0x62, 0x75, 0x6d, 0x52, 0x05, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x22, 0x15, 0x0a, 0x13, 0x47, 0x65,
// 	0x74, 0x41, 0x6c, 0x6c, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
// 	0x74, 0x22, 0x3c, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x41, 0x6c, 0x62, 0x75, 0x6d,
// 	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x61, 0x6c, 0x62,
// 	0x75, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
// 	0x6f, 0x2e, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x52, 0x06, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x73, 0x22,
// 	0x3c, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x73, 0x42,
// 	0x79, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
// 	0x12, 0x1b, 0x0a, 0x09, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
// 	0x01, 0x28, 0x04, 0x52, 0x08, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x49, 0x64, 0x22, 0x46, 0x0a,
// 	0x1e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x73, 0x42, 0x79, 0x41,
// 	0x72, 0x74, 0x69, 0x73, 0x74, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
// 	0x24, 0x0a, 0x06, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
// 	0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x52, 0x06, 0x61,
// 	0x6c, 0x62, 0x75, 0x6d, 0x73, 0x22, 0xa4, 0x01, 0x0a, 0x05, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x12,
// 	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12,
// 	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
// 	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20,
// 	0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x67,
// 	0x65, 0x6e, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x65, 0x6e, 0x72,
// 	0x65, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x79, 0x65, 0x61,
// 	0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65,
// 	0x59, 0x65, 0x61, 0x72, 0x12, 0x26, 0x0a, 0x0f, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x6d,
// 	0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63,
// 	0x6f, 0x76, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x32, 0xcc, 0x02, 0x0a,
// 	0x0c, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a,
// 	0x0b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x12, 0x19, 0x2e, 0x70,
// 	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x6c, 0x62, 0x75, 0x6d,
// 	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
// 	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
// 	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x09, 0x56, 0x69, 0x65, 0x77, 0x41, 0x6c, 0x62,
// 	0x75, 0x6d, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x41,
// 	0x6c, 0x62, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72,
// 	0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x52, 0x65, 0x73,
// 	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x41, 0x6c,
// 	0x6c, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x73, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
// 	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75,
// 	0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41,
// 	0x6c, 0x6c, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
// 	0x22, 0x00, 0x12, 0x67, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x41, 0x6c, 0x62, 0x75,
// 	0x6d, 0x73, 0x42, 0x79, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x49, 0x44, 0x12, 0x24, 0x2e, 0x70,
// 	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x41, 0x6c, 0x62, 0x75, 0x6d,
// 	0x73, 0x42, 0x79, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65,
// 	0x73, 0x74, 0x1a, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c,
// 	0x6c, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x73, 0x42, 0x79, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x49,
// 	0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x24, 0x5a, 0x22, 0x2f,
// 	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65,
// 	0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74,
// 	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
// }

// var (
// 	file_album_proto_rawDescOnce sync.Once
// 	file_album_proto_rawDescData = file_album_proto_rawDesc
// )

// func file_album_proto_rawDescGZIP() []byte {
// 	file_album_proto_rawDescOnce.Do(func() {
// 		file_album_proto_rawDescData = protoimpl.X.CompressGZIP(file_album_proto_rawDescData)
// 	})
// 	return file_album_proto_rawDescData
// }

// var file_album_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
// var file_album_proto_goTypes = []any{
// 	(*SearchAlbumRequest)(nil),             // 0: proto.SearchAlbumRequest
// 	(*SearchAlbumResponse)(nil),            // 1: proto.SearchAlbumResponse
// 	(*ViewAlbumRequest)(nil),               // 2: proto.ViewAlbumRequest
// 	(*ViewAlbumResponse)(nil),              // 3: proto.ViewAlbumResponse
// 	(*GetAllAlbumsRequest)(nil),            // 4: proto.GetAllAlbumsRequest
// 	(*GetAllAlbumsResponse)(nil),           // 5: proto.GetAllAlbumsResponse
// 	(*GetAllAlbumsByArtistIDRequest)(nil),  // 6: proto.GetAllAlbumsByArtistIDRequest
// 	(*GetAllAlbumsByArtistIDResponse)(nil), // 7: proto.GetAllAlbumsByArtistIDResponse
// 	(*Album)(nil),                          // 8: proto.Album
// }
// var file_album_proto_depIdxs = []int32{
// 	8, // 0: proto.SearchAlbumResponse.albums:type_name -> proto.Album
// 	8, // 1: proto.ViewAlbumResponse.album:type_name -> proto.Album
// 	8, // 2: proto.GetAllAlbumsResponse.albums:type_name -> proto.Album
// 	8, // 3: proto.GetAllAlbumsByArtistIDResponse.albums:type_name -> proto.Album
// 	0, // 4: proto.AlbumService.SearchAlbum:input_type -> proto.SearchAlbumRequest
// 	2, // 5: proto.AlbumService.ViewAlbum:input_type -> proto.ViewAlbumRequest
// 	4, // 6: proto.AlbumService.GetAllAlbums:input_type -> proto.GetAllAlbumsRequest
// 	6, // 7: proto.AlbumService.GetAllAlbumsByArtistID:input_type -> proto.GetAllAlbumsByArtistIDRequest
// 	1, // 8: proto.AlbumService.SearchAlbum:output_type -> proto.SearchAlbumResponse
// 	3, // 9: proto.AlbumService.ViewAlbum:output_type -> proto.ViewAlbumResponse
// 	5, // 10: proto.AlbumService.GetAllAlbums:output_type -> proto.GetAllAlbumsResponse
// 	7, // 11: proto.AlbumService.GetAllAlbumsByArtistID:output_type -> proto.GetAllAlbumsByArtistIDResponse
// 	8, // [8:12] is the sub-list for method output_type
// 	4, // [4:8] is the sub-list for method input_type
// 	4, // [4:4] is the sub-list for extension type_name
// 	4, // [4:4] is the sub-list for extension extendee
// 	0, // [0:4] is the sub-list for field type_name
// }

// func init() { file_album_proto_init() }
// func file_album_proto_init() {
// 	if File_album_proto != nil {
// 		return
// 	}
// 	type x struct{}
// 	out := protoimpl.TypeBuilder{
// 		File: protoimpl.DescBuilder{
// 			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
// 			RawDescriptor: file_album_proto_rawDesc,
// 			NumEnums:      0,
// 			NumMessages:   9,
// 			NumExtensions: 0,
// 			NumServices:   1,
// 		},
// 		GoTypes:           file_album_proto_goTypes,
// 		DependencyIndexes: file_album_proto_depIdxs,
// 		MessageInfos:      file_album_proto_msgTypes,
// 	}.Build()
// 	File_album_proto = out.File
// 	file_album_proto_rawDesc = nil
// 	file_album_proto_goTypes = nil
// 	file_album_proto_depIdxs = nil
// }
