name: CD

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'microservices/**'
      - 'docker/**'
      - 'cmd/**'
  pull_request:
    branches:
      - dev  # TODO: remove after test

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      ENV: prod
      DOCKER_COMPOSE_PATH: docker/docker-compose.prod.yaml
    steps:
      - name: Check out code into directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push microservice images
        run: |
          services=(user playlist artist album track csat genre)
          for service in "${services[@]}"; do
            docker compose -f "$DOCKER_COMPOSE_PATH" build novamusic-${service}
            docker tag novamusic-${service}:latest daronenko/novamusic-${service}:${GITHUB_SHA::8}
            docker push daronenko/novamusic-${service}:${GITHUB_SHA::8}
          done
